### ISSUE TITLE
Extract simulation / forecasting paths from tidymodel when using adam_reg

### ISSUE THREAD

**Issue by andrewbcooper** [config-i1/adam#13]
I hope this is an appropriate question here (I just realized after posting that you might not be involved with the modeltime implementation of your adam model).  I'm just starting to learn how to do time series forecasting in the tidymodel framework.  Using ADAM from the smooth package, I can do the code below to save nsims (e.g. 1000) forecasts of 10 years of data for further analysis:

library(smooth)
data(BJsales)
adamETSBJ <- adam(BJsales, "AAN")
OneKForecastsOf10Years <- forecast(adamETSBJ,h=10, interval="simulated",scenarios=TRUE,nsim=1000)

plot(OneKForecastsOf10Years$scenarios[,1], ylab="Sales",ylim=range(OneKForecastsOf10Years$scenarios), xlab="Horizon",col=rgb(0.8,0.8,0.8,0.4))

Plot all the generated lines
for(i in 2:1000){
lines(OneKForecastsOf10Years$scenarios[,i],col=rgb(0.8,0.8,0.8,0.4))
}

To do this in a tidymodel framework, I do:

library(modeltime)
library(tidymodels)

BJsales.tidy <- tibble(BJsales) %>% mutate(FakeDate = seq(as.Date('2020-01-01'),by='day',length.out = 150))
model_spec <- adam_reg(ets_model = "AAN") %>%
set_engine("adam")

model_fit <- model_spec %>%
fit(BJsales ~ FakeDate, data = BJsales.tidy)

models_tbl <- modeltime_table(
model_fit
)

But I can only seem to extract the summary stats for the forecasts, not the simulation paths

TidyForecasts <- models_tbl %>%
modeltime_forecast(
h=10,
actual_data = BJsales.tidy,
interval="simulated",scenarios=TRUE,nsims=1000
)

Any suggestions on what I'm missing? Thanks!

**Comment by config-i1** [comment]
Hi Andrew,

This is not a smooth/adam() issue. This is the question of what modeltime returns and how to access it. I'd ask the maintainer of that package to explain how to do that. As you see, the one from smooth works as intended.
