### ISSUE TITLE
default ets-model def. of auto.adam() and its interpretation in a third party lib.

### ISSUE THREAD

**Issue by Steviey** [config-i1/adam#6]
Hi!

I'm reading the book. Does this question follow the concept described in the book and comes to the right conclusion/question?...
https://github.com/business-science/modeltime/issues/162

**Comment by config-i1** [comment]
You can use any model you want. The default one is the safe option.

**Comment by Steviey** [comment]
Yes Ivan, but not "ZZZ" in the modeltime auto.adam- version, since 'ZXZ' can't be overwritten with 'ZZZ'. So I guess ZXZ is the saver version. But anyway thank you.

PS: It will be translated as follows...the default stuff is hardcoded (in modeltime)...
https://business-science.github.io/modeltime/reference/adam_reg.html
